#!/usr/bin/env python2

from subprocess import check_call


# python-shelltoolbox is installed as a dependency of python-charmhelpers.
check_call(['apt-get', 'install', '-y', 'python-charmhelpers'])


# These modules depend on charmhelpers and shelltoolbox being installed so they
# must not be imported until those packages are available.
from charmhelpers import (
    log,
    log_entry,
    log_exit,
)
from shelltoolbox import (
    apt_get_install,
    cd,
    command,
    install_extra_repositories,
    run,
)


def fetch():
    """Install required dependencies and retrieve Juju/Juju-GUI branches."""
    log('Installing dependencies.')
    install_extra_repositories('ppa:chris-lea/node.js')
    apt_get_install('bzr', 'imagemagick', 'make', 'nodejs', 'npm', 'zookeeper')
    log('Retrieving source checkouts.')
    bzr_checkout = command('bzr', 'co', '--lightweight')
    bzr_checkout('lp:juju-gui', 'juju-gui')
    bzr_checkout('lp:~hazmat/juju/rapi-rollup', 'juju')


def build():
    """Set up Juju-GUI."""
    log('Building Juju-GUI.')
    with cd('juju-gui'):
        run('make')


if __name__ == '__main__':
    log_entry()
    try:
        fetch()
        build()
    finally:
        log_exit()
