#!/usr/bin/env python2
# -*- python -*-

from subprocess import check_call


# If the user's environment has "juju-origin: ppa" set, they will
# automatically have access to python-charmhelpers and python-shelltoolbox.
# However, we want to support environments that use the non-PPA environment as
# well.  To do so, we need to install the Juju PPA, which we will do with a
# couple of functions that are actually maintained in python-shelltoolbox.
import bootstrap_utils
bootstrap_utils.install_extra_repositories('ppa:juju/pkgs')

# Python dependencies must be installed here so that the charm can import and
# use required libraries.
PYTHON_DEPENDENCIES = (
    'python-apt', 'python-charmhelpers', 'python-launchpadlib', 'python-shelltoolbox',
    'python-tempita',
)
check_call(('apt-get', 'install', '-y') + PYTHON_DEPENDENCIES)


# These modules depend on the Python dependencies above being installed so they
# must not be imported until those packages are available.
from charmhelpers import (
    get_config,
)

from utils import (
    config_json,
    log_hook,
)

from backend import Backend


def main():
    config = get_config()
    backend = Backend(config)
    backend.install()
    # Store current configuration.
    config_json.set(config)


if __name__ == '__main__':
    with log_hook():
        main()
