#!/usr/bin/env python2
#-*- python -*-

from charmhelpers import get_config

from utils import (
    log_hook,
    stop,
)


def main():
    config = get_config()
    stop(config.get('staging'))


if __name__ == '__main__':
    with log_hook():
        main()
