#!/usr/bin/env python2
#-*- python -*-

from utils import log_hook
from backend import Backend


def main():
    backend = Backend()
    backend.stop()


if __name__ == '__main__':
    with log_hook():
        main()
