#!/usr/bin/env python2
#-*- python -*-

import socket

from charmhelpers import (
    get_config,
    relation_set,
)
from utils import log_hook


def main():
    hostname = socket.getfqdn()
    config = get_config()
    port = 443 if config['secure'] else 80
    relation_set(port=port, hostname=hostname)


if __name__ == '__main__':
    with log_hook():
        main()
